enum Cards{
    LIGHTNING_BOLT = 1,
    LAVA_SPIKE = 2,
    RIFT_BOLT = 3,
    SKEWER_THE_CRITICS = 4,

    GOBLIN_GUIDE = 5,
    MONASTERY_SWIFTSPEAR = 6,
    EIDOLON_OF_THE_GREAT_REVEL = 7,
    REINFORECED_RONIN = 8,

    BOROS_CHARM = 9,

    SEARING_BLAZE = 10,
    LIGHTNING_HELIX = 11,
    SKULLCRACK = 12,

    MOUNTAIN = 13
};